name: xteamtask
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  #firebase repos
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_analytics: ^11.2.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  firebase_database: ^11.0.4
  
  #UI/UX
  pretty_animated_buttons: ^0.0.2
  rive: ^0.13.12
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2

  #state managers 
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  #maps
  flutter_map: ^7.0.2
  location: ^7.0.0
  #API's
  dio: ^5.7.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
  assets:
  - lib/assets/lottie_animations/LottieAnimationMap.json
  - lib\assets\rive_animation_presset\x_team_task_animationpresset.riv
  - lib/assets/image/clipart3004129.png
  - .env
  - .env.prod