// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVzpPz-53WhTW7NrxPMj01fS4omv_ukk',
    appId: '1:966776427944:web:b8708fecfb78fbbd82b99d',
    messagingSenderId: '966776427944',
    projectId: 'xteamtask-645c1',
    authDomain: 'xteamtask-645c1.firebaseapp.com',
    storageBucket: 'xteamtask-645c1.appspot.com',
    measurementId: 'G-GYFTN8SDCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Aqp-TDlRH2l7EKS9onpkCf5oO05z4Lc',
    appId: '1:966776427944:android:81d228ab6f04bbba82b99d',
    messagingSenderId: '966776427944',
    projectId: 'xteamtask-645c1',
    storageBucket: 'xteamtask-645c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGiLaLYKHalEiRrgCKPkXwoLTBgnyNVoc',
    appId: '1:966776427944:ios:7e046c5df2ded66c82b99d',
    messagingSenderId: '966776427944',
    projectId: 'xteamtask-645c1',
    storageBucket: 'xteamtask-645c1.appspot.com',
    iosBundleId: 'com.example.xteamtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGiLaLYKHalEiRrgCKPkXwoLTBgnyNVoc',
    appId: '1:966776427944:ios:7e046c5df2ded66c82b99d',
    messagingSenderId: '966776427944',
    projectId: 'xteamtask-645c1',
    storageBucket: 'xteamtask-645c1.appspot.com',
    iosBundleId: 'com.example.xteamtask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWVzpPz-53WhTW7NrxPMj01fS4omv_ukk',
    appId: '1:966776427944:web:0931a2b5c0b96bea82b99d',
    messagingSenderId: '966776427944',
    projectId: 'xteamtask-645c1',
    authDomain: 'xteamtask-645c1.firebaseapp.com',
    storageBucket: 'xteamtask-645c1.appspot.com',
    measurementId: 'G-FSVXKG9KTF',
  );
}
