name: Flutter PR

on:
 workflow_dispatch:


jobs:
 build:
   runs-on: ubuntu-latest
   env:
      JAVA_VERSION: "17.0"
      FLUTTER_VERSION: "3.24.3"
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
          java-version: $
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: $
    - run: apt-get install lib32stdc++6
    - run: flutter pub get
    - run: flutter build apk --release