name: Flutter PR

on:
 pull_request:
  branches:
    - '*'
 push:
  branches:
    - 'main'

jobs:
 build_macos:
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter clean
    - run : flutter upgrade --force
    - run: sudo softwareupdate --install-rosetta --agree-to-license
    - run: flutter pub get
    - run: flutter doctor -v
    - run: flutter build apk --release

 build_windows:
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter doctor -v
    - run: flutter build apk --release
  
 bnild_ubuntu:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter doctor -v
    - run: flutter build apk
