name: Flutter PR

on:
 workflow_dispatch:


jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: $
    - run: flutter pub get
    - run: flutter build apk --release