name: Flutter PR

on:
 pull_request:
  branches:
    - '*'
 push:
  branches:
    - 'main'

jobs:
 build:
   runs-on: ubuntu-latest
   env:
      JAVA_VERSION: "17.0"
      FLUTTER_VERSION: "3.24.3"
   steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: flutter build apk --release
    
