name: Flutter PR

on:
 pull_request:
  branches:
    - '*'
 push:
  branches:
    - 'main'

jobs:
 build_ubuntu:
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - name: "env creator"
      run: |
        echo OPENWEATHER_API_KEY = ${{secrets.OPENWEATHER_API_KEY}} >>.env
        echo OPENWEATHER_API_KEY = ${{secrets.OPENWEATHER_API_KEY}} >>.env.prod
    - run: flutter doctor -v
    - run: flutter build apk --release

 build_windows:
  runs-on: windows-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - name: "env creator"
      run: |
        echo OPENWEATHER_API_KEY = ${{secrets.OPENWEATHER_API_KEY}} >>.env
        echo OPENWEATHER_API_KEY = ${{secrets.OPENWEATHER_API_KEY}} >>.env.prod
    - run: flutter doctor -v
    - run: flutter build apk --release
    
